[tool.ruff]
line-length = 100
indent-width = 4
target-version = "py312"
extend-exclude = ["venv", "misc/model"]

[tool.ruff.lint]
extend-select = ["I"]  # check and fix imports
ignore = ["E741"]


[tool.mypy]
exclude = [
    "^misc/model",
    "^data",
]
